### ISSUE TITLE
train_dataset should be a dataset not an iterator

### ISSUE THREAD

**Issue by matprst** [fvlieshout/ATCS_group1#3]
Currently ```train.py``` throws an error for me: ```TypeError: 'BucketIterator' object is not subscriptable```. 

The issue comes from [this line](https://github.com/fvlieshout/ATCS_group1/blob/c3b57c219d154927f9bd859e7a9206e31744a692/train.py#L57). The iterators returned from ```get_data_splits()``` are not datasets but dataloaders.

One way to solve that could be to not pass a dataset to the trainer at all but instead implement ```get_train_dataloader()```, ```get_eval_dataloader()```, and ```get_test_dataloader()``` ([see](https://huggingface.co/transformers/main_classes/trainer.html)). That would require to overwrite ```Trainer``` with our custom "roberta trainer". There are probably other (and better) ways we can discuss.

**Comment by rahelbeloch** [comment]
Yes, I was aware but somehow wanted to push at least the bit of code that I already had. I feel like that we can not simply use the torchtext iterator in the huggingface library, but manually have to create dataloaders from the datasplits. I tried your suggestion and simply return the iterators from torch text in the methods `get_eval_dataloader ` etc, but this does not work work right away. It still expected the torchtext dataloader instead of an iterator:


<img width="1107" alt="Screenshot 2021-04-30 at 13 57 37" src="https://user-images.githubusercontent.com/8261902/116692040-07847880-a9bc-11eb-84f5-cef39a1335de.png">

Will continue later working on this.

**Comment by rahelbeloch** [comment]
Done in the PR cooporation of Mat and Rahel
